program <- comment backslash whitespace*

comment <- (";" (!newline .)*) / nested_comment
nested_comment <- "#|" comment_text comment_cont* "|#"

comment_text <- (!comment_text_taboo .)*
comment_text_taboo <- "#|" / "|#"
comment_cont <- nested_comment comment_text

atmosphere <- whitespace / comment
intertoken_space <- atmosphere*

whitespace <- (intraline_whitespace / newline / return)
newline <- [\n]
return <- [\r]
intraline_whitespace <- [ \t]

backslash <- [\\]